services:
  postgres:
    container_name: postgres-bs
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_store
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-bs
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgres:
    driver: local

networks:
  spring-demo:
    driver: bridge